mainSections = ["posts"] # use it for blog page section 

uniqueHomePage = true # change to false to add sidebar to homepage

repo = "https://github.com/onweru/compose"

time_format_blog = "Monday, January 02, 2006"
time_format_default = "January 2, 2006"
enableDarkMode = true # set to false to disable darkmode by default # user will still have the option to use dark mode

# sets the maximum number of lines per codeblock. The codeblock will however be scrollable and expandable.
codeMaxLines = 10

# disable showing line numbers by default. Switch to `true` if you'd rather have them on.
codeLineNumbers = true

# Site logo
[logo]
  lightMode = "images/Logo_scriptural-lightm.png"
  darkMode = "images/Logo_scriptural-darkm.png"

[source]
  name = "Mon GitHub"
  iconLight = "images/GitHubMarkLight.svg"
  iconDark = "images/GitHubMarkDark.svg"
  url = "https://github.com/kassifer/"

# optional
# attribution. Feel free to delete this
[author]
  name = "Maël JEMETZ"
  url = "https://www.linkedin.com/in/jemetz-maël"
